# Generated by Django 3.1.7 on 2021-03-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidstatistic',
            old_name='date',
            new_name='case_date',
        ),
    ]
