# Generated by Django 3.1.3 on 2020-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
