# Generated by Django 3.1.7 on 2021-03-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_drug_category_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='category_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.drugcategory'),
        ),
    ]
