# Generated by Django 3.1.7 on 2021-03-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20210306_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='category',
        ),
    ]
