# Generated by Django 3.1.7 on 2021-03-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_remove_drug_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='category_new',
            new_name='category',
        ),
    ]
