# Generated by Django 3.1.7 on 2021-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20210306_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='country',
            new_name='country_name',
        ),
    ]
