# Generated by Django 3.1.7 on 2021-03-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user'),
        ('drugs', '0009_auto_20210313_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country'),
        ),
    ]
