# Generated by Django 3.1.7 on 2021-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_drug_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='producer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
