# Generated by Django 3.1.7 on 2021-03-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20210313_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='producer',
            new_name='producer_id_s',
        ),
    ]
