# Generated by Django 3.1.7 on 2021-03-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20210306_1501'),
        ('drugs', '0013_auto_20210313_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StoreDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
