# Generated by Django 3.1.7 on 2021-03-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_auto_20210313_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boughtdrugs',
            old_name='buy_date',
            new_name='created_at',
        ),
    ]
