# Generated by Django 3.1.7 on 2021-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_auto_20210313_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtdrugs',
            name='buy_date',
            field=models.DateTimeField(null=True),
        ),
    ]
