# Generated by Django 3.1.7 on 2021-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0016_boughtdrugs_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedrugs',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
