# Generated by Django 3.1.3 on 2020-12-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
    ]
