# Generated by Django 3.1.7 on 2021-03-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='city',
            new_name='city_old',
        ),
    ]
