# Generated by Django 3.1.7 on 2021-03-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_city_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='city_old',
        ),
    ]
