# Generated by Django 3.1.7 on 2021-03-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_store_city_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='city_new',
            new_name='city',
        ),
    ]
