SELECT COUNT(DRUGS.NAME)
FROM DRUGS
INNER JOIN DRUGS_STOREDRUGS D ON D.DRUG_ID=DRUGS.ID
INNER JOIN STORES S ON S.ID=D.STORE_ID
WHERE DRUGS.CATEGORY_ID = (SELECT ID FROM DRUGS_DRUGCATEGORY WHERE NAME ='Дерматологические средства » Ранозаживляющие препараты') AND S.NAME = 'Социальная аптека Maximus'
